[[CDE]]
arch = "aarch64"
git-tree-sha1 = "ea8bd63811d8d273eebcc255df7ac715c649937b"
libgfortran_version = "5.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "2de30edb0b936ba5e996a99ae2a4b47d14d9a2ff51c97e52dbb7da4df5bfb27a"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "609979d3bafd4ff41eee32a66b3f0e7e6ac67fb8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "3c12c38a43def30e7e56334913e45ab19ffec35d84466252d165ffea6f68ef21"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "3071f62516a75cf23f5297e6e8642a14533d0218"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c30f6e3d366bbe7f3bcc3ac9e862e9094284ecdc0aa1681a12a5b3d873b50af7"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "1d89f660326210f3c620c5b9158ec27303d69f9e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "aa9ad89c6a255040ef775873e1f4ef978688316953691ddda5bd1e52d4420e6f"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "d5bb1d2f0a71b5405887de719102d220bb9cc5ad"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "7295e32037bda28d9c51200f4eda94e43e7ef1f69a9e02f40d25b5987f3dc963"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "44b4b5b7fdd351acca23003b6c99bcaa78eeb55d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "fdc6018b184ff5467e917e7a1a1d42be05ccba836df1a45106472915b3bac2ea"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "65c40af7b5f31c524f66b8940b7d0dc2d048eb96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "f5812f3a366e7819f6c063a5bc88a5db6cebe5aa2eb19abab23142e018373ebf"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c28ceba03671d62e9c6db77b91315f06fccb4a40"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "aff86f79ada41ef730f3a947e753557300057727eaee5b280a3857983699bc6d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f2526d925de3766e1b49d2fcaaf9288a8cb79e9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "fbcb684fd23282d3de86179406c1a55529c22488790e77b4b7b4a41a204d1e18"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f94c549437604a5ab9aef482767725b31d4da7f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "8f0923f2b0735d28e65d171afec7ad2aa831f697a3dc763b80cbd6c0e511b18d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f53079ddde7eb36c579e4c22c63c6c7dd464b9a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "2fb9d9581c7ac123d14ea07631023091dbd2520054399d883cf56a2f789308cd"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce6826f4db2756d388403e5ec5928bff9041ebd5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "2f2c51c5be33a94b23c70bb80e682c5a24bf4a54c817a743617b71181a368e3e"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c50657fbe3d6033670bfa36d643094ac13eb3f99"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "010ff62e04119b8e41ed5172273e264ce40b94cea217c23fd38461acc4e82e61"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d8833f7c94f265a777be7cfcea97e485a4239b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "5365b75709028580c156d7ceff13cc0ae1692eeb7b053bb3a4cef0b056c6b2f4"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9525ef768c19af35721a7052877bbfa070806d68"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "ad36064cfbd3d75ddb93add581ea8c449c5e5d8a567c2d906c3b5741ded0b8f0"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90d22c4a32b43ce933cc091df06d41beeaefdbc1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "9ba16e963b5369f7e564558a4297528a0857b48f57c333caf4e945487ff06b65"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf20ea3afccfcd0294c901692c07d14ea71eebea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "5784e3d8cdd1c1db02fad43473cb46965096c56b93e7d1337a4eaff41163de1b"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71de0405ab4bc245ec382a83f1efaca05eb26e3b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "50980c802f80c23734ff39a54f369756fec9b6d104aa10cabf8f71bfb59c6203"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a42eabef677264003dccd0f585feff301c1003e3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "63fabd49ef5ea3ad5ca89e6965d99116cee05a9289f70b5bc24b578a7a26a186"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "0051663583706d42723287d561010b71eec88f4e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "6c66c47f76c998ad4e16abccd96665b1c5d92a0dc798d8d578e609f9b509ba20"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "520b1f84b60152d9eeba9eb6c6e5b7b1f4c54585"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "da734d79a751a3dcc77eca62c6a63c4a48de0dafdf70e592bd22479d14f3d29d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "a14eb17bbb484ab3c8bbd4a3f9dd5c7a4e125899"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "a9e9906c0a7c9caac747bf647eb9ed6f41f6ea8b19f795c24b8adbe3f2c10eca"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "87ba9d3faa22c59b95bac9694f242ddb3fc9765c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c095137769223bec09500904b50319aa58022b95e019b367c6f4232f2f51b420"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "cb1c86c9a7ca3d7c5f45d6a69e33a2b0a496535a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "14fe47dcde52d09a28fb8ea7b504dbc8e89d1726332003de59b180b04a4719f4"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "14690eeadcb797d940d5af2c39cedc5281083a50"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c23f2343d6661e6d5648d9a997b39a92f2241e020c91a4f5199c68af8cdbb3f1"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "98168cdef7fb54fcca9de7caae06e0e5f983d91a"
libgfortran_version = "3.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "1ec7164d3247a8469362125bd497b6cacae8df4560ae1da3df0e81037d06e549"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "b55017dd98dcaa00cac98dbba96c77ec934e2968"
libgfortran_version = "4.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "3768a98a3c8c426652c98e13920b2d93b5079eabf64b084a9e94f29139dc58b7"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "f336bf3f5787ea90d16a16ca41fe6f9ba2915e15"
libgfortran_version = "5.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "f1d47f506c2c726d367c8b84036a1f87e42b086a3c450b49d4a73cdecfee3ae9"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "5b6a3f9e487555e1cc955853716d48d770d9a403"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "bf0d9694c472cd5d96273ee09ec9eabe73b85e67d393d2792d2b28f30a30d768"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "88fe373f2b9bb04016de6a0a3faea4195515eebd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "bc6876130010dc83f68a25b040ece808b7bb386d04df6e644cd99612cb761144"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "24dcc5ee37266959bd86034c4dd2c37c546dc7c5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "296da12ee1f391107025b093ebcd80bc1c749cfdbc58d46747452acf3b720f73"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "eb6e8c63da38ac4487c22e9a03c2a24d50cd1f36"
libgfortran_version = "3.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "71062d34dfed618d2bde7d08e9afce096afc8c4bc2ea91aca904eb0ce298792f"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "eab906ce2eb71f384f9d2d6698bae6b4d1ed7adf"
libgfortran_version = "4.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "06fce92a1132c57b486ed870ce57f1d18af577902b8a23da1f49be4b9c4a2553"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "fd7b3f47d1df48f65f23f1aee555618ab5ff50c2"
libgfortran_version = "5.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "4ae5b782ae178ec2f89769109676cf8254b1657bda9f27c0a6b8068d80074d22"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "f27cda69ebce03d8dc5fbf73c1ca0dc66e634a58"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c9ca92da4c91a1f16a1d7110c2d1ebff6ccff466c6a8c02ac5c0a24b38cc77b1"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "66d954273e72a17da930f11a92a66e4889727820"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "4a19dc151ea3a3a31359f4d0230546b0f23d0cb009a7decefb68bfcf4a14b800"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "8e90c5f64384d9544bc3ed1bfca06c8c373e768f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "f97c045ad716cc0f004de9465d7853e7c2243cb3dbe7b635955a697a72733520"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "abe8e9a28706900c1ec4a906e067cbb09a93107b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "e5b6cbee7cec06ccacb4bee483132464f4c2a5c3e6b8328ed71e3cbf8df57954"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "7e437fee0303cb5db357425bc982b37fb06c9795"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "b35ff647ed9b6abd634f18e19c61d40c5c64cf7da48858d8dfbd2256426f8768"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "78395b670006cda4a142c53e75df62ac613a29cf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "ab4fdad5b7e8764bb3ba66edb9109fb565779314c8575c92e33942f79251b204"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "c17ac9e1547dbbee55c1096215aaa5fd4c53c17d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "a38908d904a025e1bf268474d3924c28e47238985e841e58e7a498080c2a6b3b"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "add192e03f9b73c54b5f9a2a745be3f8eaaf4bc3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "4edb577058a095e50dbfe3d01da550d7133a77f60beb673960a1da21c2b92f0c"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "5cd4b640b7b86f8dd63a7ce0af8aeca55f53bfb6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "2a1efb3f790270246045b4622c259adcc4fc710f4670ea3395c44862b7482f89"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "5bf18d21a31b72b501f5fd7c24ba4b558bb4bc93"
libgfortran_version = "3.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "aed7e1217c25c2c30f3162d8442f93b86226391c449dadbf39c25ad858cdacc8"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "1a021287e1983caf30333d695890460bf67ff101"
libgfortran_version = "4.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "960002bf4a4dada504e1776f0ea35e4f93149f3214c55911317b17db44c4078e"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "36e199f83873cdfcc5babd692e52b0fa5467b429"
libgfortran_version = "5.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "c912bab3b06c16b8abe9f454f1ee408e67115b41d6655f15823a34407bfcbdcf"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.1+0/CDE.v1.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
