[[CDE]]
arch = "aarch64"
git-tree-sha1 = "8ef0c10c34c155e7421b67c6bd6453ba85f353a7"
libgfortran_version = "5.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "908bf6a078c18a256e2088639490f04fde751e29fb2f8ea7fc9a0bd5308e2a01"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "0433d8956313274a0186fb2f2f2733c55cab3824"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "5bf65dfa5a55c9b37a6c43769a91c2e2a503e105d19a9a065b7b1b2e125d131d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "da0dae68d2f90ee899923f1d4faf1419a81f04b9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "4943b58ab01a5859da600a10ef7504deadfa125ca459bba8e30594c9a9e1eae1"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "390b2ac74f4fe99839b22aa64bcdb816547fb851"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "7ddbe6f0a0974855d85221317f59bfdea8251bfa3f0887037c8f95f96857298a"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "cec019be6fac0f2881768393222c7f87f5816938"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "384ad140e5038368ca0a6744906099b733c00efc9ccd3c78324dc752722b47b7"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "2ff28eae521259e731648258643a075538dd9067"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "13402495e0ccefdc2cbdbaf9eace47bd0b1408e19e6d85cec0b5c6b19f3b686c"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "aarch64"
git-tree-sha1 = "8aea65784f59b11b6c84a39273f9930bc6f329c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "6fe1bbbfba0d39cd08af6e1471ea1c262f948ecbe0538c46c426528e6aa2883d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b45f5c39313e8cfcc5447c4b679916c0158f82ee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "505f46185711424bd6b24f4c59bd1869478a40b63f27d36bbd6bfd4ea43f5e4d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81bcc001f25573d2719b18c772f3d33167b0a986"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "7fe6d854f2f7002051d0401ab8120a6f2c1b37c10191e4e0fe34792be45c2c60"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c304a6bb268def584d625849c8f78bfbc4856ed9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "901a171df96cf4285d270639eb2dac72436b9bbdfd607d4485396d09d515e6aa"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "beb48e1a039113f0c421a434aa9a98ce079f9666"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "ee88e6d32d0deb151afe888c973e349e957ac1519d9bb8820cd5c33429ff4082"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "073fc80848c451e4f0b77164e5fb0fc5885f7a6b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "413e8c553e58be93fe634046e72cf5727973d9ae47d750d817a342ac174ea234"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a434e1845bc1f75249425ebfefd6bb891feafa7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "82e7ba6f7dec5ba2c2b98d456fead3098315d7037139f6e052754e31a266696b"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea12c05a0858a965974d39ed1c8931e1e4518632"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "5e89d90fec5ab427b4750a1fd67294d608f33e0410232458963f39aa637a05f3"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8719f9f413f7b19d5ba1241669a888c2bd02b3f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "ee413d0235f1637d6af7c7c57b88d1000d92e79d1d30f11cff691a2e332a7874"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96093684c074177c9de19465531d1a4862546b93"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "1f86b82f273f526ee0863db1a9ff9e105da4426d2ac495e3c5c8fe51b6f614c1"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a363a4190e98572fc98da7646b6f10f9f00d081d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c4036cb15671999c2b810734b5fe228bc3b10dc7fafcc882dc26583e4cc843b5"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae4eae632458868879abab26f0c489bd6ad9f699"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "36741b469e6cc6cfe73ac92b5f05a5fdd83509fc408cac40056ee4ad62bb6eb8"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[CDE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf0a74c39460dd421fed868d9b948dc8eaa3d51b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "a11d3f442c141dad03e24ae02bfbadd26cc5c79be5e08cc177326603dccf07b3"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "8c6d4bcb99c0d2ac5787514816ca8dc040d9092b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "960e0532a9864a98dc7c3fc761dd65cde45e3c6a5d1228ca2173addb99d3bccf"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "0268f56d56b9a1d0836b72d6b23274f8c339b745"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "9674f1ca36955233c644dc6caa2da852d2c0d67593ff89a45854764fc1ddad35"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "2f04eba1041f1a5e5f2b06865eaa291f3fe0c152"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "b884adf1633dd7d18e39229fbcb683b6d1eb2f03bbd65cbbfe91a56178f53487"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "cdb538a85323a7a0cdbd53ef31197b51983368e2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "ec610a1c0511fee14e98a20c195faaa39ffa6263962d98034bb41271729c8bca"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "bf29b97b9a7faf8241d507ea9b85b79a3ce32251"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "80fcf2bc65578398cd5194d20795773dc81c665dd4adb28cd22c7e9f07a3b9a8"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "093604f3005d65a025dfe097589df9d6481657fd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "0aaa8c93c54324a7597d5de8d9ef342d58238da82a12fd72161ee94a6220c981"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "8d7dbe6916041d275d3537ef1dadce012b664ee9"
libgfortran_version = "3.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "a6093775fa56065e4cdd2263d1853572d4a2124254fcf4f4ecab0a31e7924d4f"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "395f944fbd3c492fe8ce2f46c66c586dbdcba4c2"
libgfortran_version = "4.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "2aaeaa53b0650d51c8dc5bbea8f60d664b4fef01d2612e5dec8fbac7bebe67d1"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[CDE]]
arch = "i686"
git-tree-sha1 = "086a58dfb0c3f64c310e30fd39893f568f8c5232"
libgfortran_version = "5.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "5dc1985b51e5c897174db8c8c63297398674b0f6bcd96bc215368a17b47a6ce7"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "d25bc5f87340416d922653d16caec045fcb75977"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "0e784a79264891b87afdf562d932c0c785adf999488324f9cef52e6d4a7af029"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "19e1102ed19e360465cfba759e06a0d4113c5559"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "9880c0eb822f64b1dad40b83ada026a0f229d33bfcdf9974502f75fd5a4f6219"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "powerpc64le"
git-tree-sha1 = "948207c5670e0499ca2d9c6616aba5381517b8e5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "b70329a22ba85f9963a262ff9702b226063a0fdda4e2fd02d253733a3f454547"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "068ec9fae12b82215cee58d029348a412d995af1"
libgfortran_version = "3.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "1255c0dc8e1543d5637535c3af9f345be38af1f2bb6f4910c6b767d3f3a7d80c"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "0333080dbe164736b950522795cc63fea6653279"
libgfortran_version = "4.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "c9a0a6b822a9422bdf70523bec9b35e5d7483f23a9fdb9a87fa942dd9e80235b"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "b1b04202b24b7ad27c513147e4b504f41f52bb73"
libgfortran_version = "5.0.0"
os = "macos"

    [[CDE.download]]
    sha256 = "f63c99f06020e1125122b43b56a19eff9d9f54df8ede9e126af036e8b5e91c0c"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "54670f178ff2e5e01b496d177af72af5126ad2e1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "7587c682b429263c6232279f8582df8949ff2fcf5abcf21c49c580c5208a757d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "84e5928721461faaba26040dc4be90e507304521"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "c87131bf250938345758f839941f6fd80f44804a4bfba033cb64f54eebf144bb"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "6a2166f24ea0a7ad19bb2c8494423bee5abe9f08"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "a02b816dbb0c6f20d06854c3f5948c76d5006e7fd07e301928712dd02a24d91f"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "f1b8a43809ede474e148d9259b44df739a7bb6ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "61cab90a17479f23d43c34aed11e7b78044a5c2d306123e855b535451a54680a"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "398c1206e5f24d61ce19cc2cbd41d11d9b0e50f8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "5e6eeb2cf196669f9525a807abc006443f85947961c236e4dde9d5e49d44622a"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "0ad9011f9f0df8c3d50dbb41128850a362fb6f54"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CDE.download]]
    sha256 = "02820a21c144486dae3c09c1a7e53ed256992d6915ca1c97638573db7309dbf2"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "303be72d083ffb4b672b837a395b0033ddbfbcaa"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "4055e841f5105444fb8ef8029dc900e357f4cd0119ddc97f1359276873008e6b"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "8fab1defee4f5f53ea3043ae84ba9a55a88a56c8"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "a892a9156ad10a455ec23f1b1ec8d3e89c2ef17392ec3e290ca9af08272fc0c0"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "c29b867a9e6657ab5db8457a6cce28e1b9f2ecf0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CDE.download]]
    sha256 = "28da92dc0083214882e92bee2482c2a48282212d95ac45fd554edd9a3dad62a0"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "0c0fad8ff0b3f5e6d48cc6d5de8a42d37a2afea5"
libgfortran_version = "3.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "e986fade198fbe48d735f453421d10078a3af4a5f9fb8e7be6b0cf763ad826fa"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "59d0c05a5e994b61a4df02796293db22cc581a33"
libgfortran_version = "4.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "375af4d7434fa434933841bf1673ec8b63fd9ab5851ede4f36e6e526bf81e3ff"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CDE]]
arch = "x86_64"
git-tree-sha1 = "642df406f7e739b6f6229c0dffbf50b0a33eb0b9"
libgfortran_version = "5.0.0"
os = "windows"

    [[CDE.download]]
    sha256 = "8487e0958d7ad0100d8f17aedb97c851a2b1da650b73dbfd40eaf64ebd82ce3d"
    url = "https://github.com/JuliaBinaryWrappers/CDE_jll.jl/releases/download/CDE-v1.0.2+0/CDE.v1.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
