# Autogenerated wrapper script for CDE_jll for i686-w64-mingw32-libgfortran4
export run_cde

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("CDE")
JLLWrappers.@declare_executable_product(run_cde)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        run_cde,
        "bin\\cde.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
